common: &default_client
  options:
    write:
      w: <%= ENV['MONGOID_WRITE_MODE'] || 1 %>
    read:
      mode: :<%= ENV['MONGOID_READ_MODE'] || 'primary' %>
    max_retries: <%= ENV['MONGOID_MAX_RETRIES'] || 1 %>
    retry_interval: <%= ENV['MONGOID_RETRY_INTERVAL'] || 0 %>
    timeout: <%= ENV['MONGOID_TIMEOUT'] || 0.5 %>
    ssl: <%= ENV['MONGOID_USE_SSL'] || false %>
    # TODO: Fix hack for Edraak. Move into config variables.
    auth_mech: :scram
    connect: :replica_set
    replica_set: Forum-prod-shard-0
    ssl_verify: false
    auth_source: admin

common_uri: &default_uri
  uri: <%= ENV['MONGOHQ_URL'] %>

development:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

test:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

production:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

edgeprod:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

edgestage:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

staging:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

loadtest:
  clients:
    default:
      <<: *default_uri
      <<: *default_client

defaults: &defaults
  use_utc: false
  use_activesupport_time_zone: true
